steps:
  - label: 'stack rebuild'
    env:
      STACK_ROOT: "/build/ouroroboros-network.stack"
    command:
      - "rm -rf /build/ouroroboros-network"
      - "cp -R . /build/ouroroboros-network"
      - "cd /build/ouroroboros-network"
      - "nix-build scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    agents:
      system: x86_64-linux

  - label: 'stack-cabal-sync'
    command: 'nix-shell scripts/buildkite/stack-cabal-sync.nix --run scripts/buildkite/stack-cabal-sync.sh'
    agents:
      system: x86_64-linux

  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux
